---
title: "Included fonts"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{included-fonts}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(gfonts)
```


```{r, echo=FALSE}
library(htmltools)
make_example <- function(class) {
  tags$div(
    class = class,
    tags$blockquote(
      tags$p(HTML("&Eacute;coutez !")),
      tags$p(HTML("Puisqu&rsquo;on allume les &eacute;toiles,")),
      tags$p(HTML("C&rsquo;est qu&rsquo;elles sont &agrave; quelqu&rsquo;un n&eacute;cessaires ?")),
      tags$p(HTML("C&rsquo;est que quelqu&rsquo;un d&eacute;sire qu&rsquo;elles soient ?")),
      tags$br(),
      tags$p(HTML("Vladimir Ma&iuml;akovski &ndash; &Eacute;coutez !"))
    ),
    tags$p(
      paste(letters, collapse = "")
    ),
    tags$p(
      paste(LETTERS, collapse = "")
    ),
    tags$p(
      style = "font-weight: bold;",
      paste(letters, collapse = "")
    ),
    tags$p(
      style = "font-weight: bold;",
      paste(LETTERS, collapse = "")
    ),
    tags$p(
      style = "font-style: italic;",
      paste(letters, collapse = "")
    ),
    tags$p(
      style = "font-style: italic;",
      paste(LETTERS, collapse = "")
    )
  )
}
```



## Roboto {.example-roboto}

```{r}
use_pkg_gfont("roboto", selector = ".example-roboto")
```

```{r, echo=FALSE, results='asis'}
make_example("example-roboto")
```



## Open sans {.example-open-sans}

```{r}
use_pkg_gfont("open-sans", selector = ".example-open-sans")
```

```{r, echo=FALSE, results='asis'}
make_example("example-open-sans")
```


## Lato {.example-lato}

```{r}
use_pkg_gfont("lato", selector = ".example-lato")
```

```{r, echo=FALSE, results='asis'}
make_example("example-lato")
```



## Montserrat {.example-montserrat}

```{r}
use_pkg_gfont("montserrat", selector = ".example-montserrat")
```

```{r, echo=FALSE, results='asis'}
make_example("example-montserrat")
```



## Alegreya {.example-alegreya}

```{r}
use_pkg_gfont("alegreya", selector = ".example-alegreya")
```

```{r, echo=FALSE, results='asis'}
make_example("example-alegreya")
```



## Nunito sans {.example-nunito-sans}

```{r}
use_pkg_gfont("nunito-sans", selector = ".example-nunito-sans")
```

```{r, echo=FALSE, results='asis'}
make_example("example-nunito-sans")
```



## Baloo {.example-baloo}

```{r}
use_pkg_gfont("baloo", selector = ".example-baloo")
```

```{r, echo=FALSE, results='asis'}
make_example("example-baloo")
```



## Happy monkey {.example-happy-monkey}

```{r}
use_pkg_gfont("happy-monkey", selector = ".example-happy-monkey")
```

```{r, echo=FALSE, results='asis'}
make_example("example-happy-monkey")
```



## Henny Penny {.example-henny-penny}

```{r}
use_pkg_gfont("henny-penny", selector = ".example-henny-penny")
```

```{r, echo=FALSE, results='asis'}
make_example("example-henny-penny")
```







